services:
  db:
    image: postgis/postgis:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: mos
      POSTGRES_PASSWORD: mos
      POSTGRES_DB: mos_transport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: